image: Ubuntu
install:
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
artifacts:
  - path: dist
deploy:
  provider: GitHubPages
  artifact: dist
  branch: gh-pages
  on:
    branch: main